package com.wondersgroup.scxj.portal.modules.news.entity;

// Generated 2014-1-20 14:16:03 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Wcmdocument generated by hbm2java
 */
@Entity
@Table(name = "WCMDOCUMENT_1")
public class Wcmdocument implements java.io.Serializable {

	private Long docid;
	private Long docchannel;
	private Long docversion;
	private Long doctype;
	private String doctitle;
	private Long docsource;
	private Long docsecurity;
	private Long docstatus;
	private Long dockind;
	private String doccontent;
	private String dochtmlcon;
	private String docabstract;
	private String dockeywords;
	private String docrelwords;
	private String docpeople;
	private String docplace;
	private String docauthor;
	private String doceditor;
	private String docauditor;
	private Long docoutupid;//置顶标志，越大置顶级别越高
	private Date docvalid;
	private String docpuburl;
	private Date docpubtime;
	private Date docreltime;
	private String cruser;
	private Date crtime;
	private Long docwordscount;
	private Long docpro;
	private int rightdefined;
	private String titlecolor;
	private Long templateid;
	private Long schedule;
	private String docno;
	private Long docflag;
	private String editor;
	private String attribute;
	private Long hitscount;
	private String docpubhtmlcon;
	private String subdoctitle;
	private Integer attachpic;
	private String doclink;
	private String docfilename;
	private Long docfromversion;
	private Date opertime;
	private String operuser;
	private String flowoperationmark;
	private String flowpreoperationmark;
	private String flowoperationmaskenum;
	private String docsourcename;
	private String doclinkto;
	private String docmirrorto;
	private String randomserial;
	private String postuser;
	private Integer ispageimg;
	private String publishdate;
	private String pagenum;
	private String pagename;
	private String pdffilename;
	private String pageimagefilename;
	private String map;
	private String yinti;
	private Long siteid;
	private Long srcsiteid;
	private Date docfirstpubtime;
	private BigDecimal nodeid;
	private BigDecimal orderid;
	private String crdept;
	private Integer docform;
	private String doclevel;

	public Wcmdocument() {
	}

	@Id
	@Column(name = "DOCID", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getDocid() {
		return this.docid;
	}

	public void setDocid(Long docid) {
		this.docid = docid;
	}

	public Long getDocchannel() {
		return this.docchannel;
	}

	public void setDocchannel(Long docchannel) {
		this.docchannel = docchannel;
	}

	@Column(name = "DOCVERSION", nullable = false, precision = 10, scale = 0)
	public Long getDocversion() {
		return this.docversion;
	}

	public void setDocversion(Long docversion) {
		this.docversion = docversion;
	}

	@Column(name = "DOCTYPE", nullable = false, precision = 10, scale = 0)
	public Long getDoctype() {
		return this.doctype;
	}

	public void setDoctype(Long doctype) {
		this.doctype = doctype;
	}

	@Column(name = "DOCTITLE", nullable = false, length = 1000)
	public String getDoctitle() {
		return this.doctitle;
	}

	public void setDoctitle(String doctitle) {
		this.doctitle = doctitle;
	}

	@Column(name = "DOCSOURCE", nullable = false, precision = 10, scale = 0)
	public Long getDocsource() {
		return this.docsource;
	}

	public void setDocsource(Long docsource) {
		this.docsource = docsource;
	}

	@Column(name = "DOCSECURITY", nullable = false, precision = 10, scale = 0)
	public Long getDocsecurity() {
		return this.docsecurity;
	}

	public void setDocsecurity(Long docsecurity) {
		this.docsecurity = docsecurity;
	}

	@Column(name = "DOCSTATUS", nullable = false, precision = 10, scale = 0)
	public Long getDocstatus() {
		return this.docstatus;
	}

	public void setDocstatus(Long docstatus) {
		this.docstatus = docstatus;
	}

	@Column(name = "DOCKIND", precision = 10, scale = 0)
	public Long getDockind() {
		return this.dockind;
	}

	public void setDockind(Long dockind) {
		this.dockind = dockind;
	}

	@Column(name = "DOCABSTRACT", length = 2000)
	public String getDocabstract() {
		return this.docabstract;
	}

	public void setDocabstract(String docabstract) {
		this.docabstract = docabstract;
	}

	@Column(name = "DOCKEYWORDS", length = 200)
	public String getDockeywords() {
		return this.dockeywords;
	}

	public void setDockeywords(String dockeywords) {
		this.dockeywords = dockeywords;
	}

	@Column(name = "DOCRELWORDS", length = 200)
	public String getDocrelwords() {
		return this.docrelwords;
	}

	public void setDocrelwords(String docrelwords) {
		this.docrelwords = docrelwords;
	}

	@Column(name = "DOCPEOPLE", length = 200)
	public String getDocpeople() {
		return this.docpeople;
	}

	public void setDocpeople(String docpeople) {
		this.docpeople = docpeople;
	}

	@Column(name = "DOCPLACE", length = 200)
	public String getDocplace() {
		return this.docplace;
	}

	public void setDocplace(String docplace) {
		this.docplace = docplace;
	}

	@Column(name = "DOCAUTHOR", length = 200)
	public String getDocauthor() {
		return this.docauthor;
	}

	public void setDocauthor(String docauthor) {
		this.docauthor = docauthor;
	}

	@Column(name = "DOCEDITOR", length = 50)
	public String getDoceditor() {
		return this.doceditor;
	}

	public void setDoceditor(String doceditor) {
		this.doceditor = doceditor;
	}

	@Column(name = "DOCAUDITOR", length = 50)
	public String getDocauditor() {
		return this.docauditor;
	}

	public void setDocauditor(String docauditor) {
		this.docauditor = docauditor;
	}

	@Column(name = "DOCOUTUPID", precision = 10, scale = 0)
	public Long getDocoutupid() {
		return this.docoutupid;
	}

	public void setDocoutupid(Long docoutupid) {
		this.docoutupid = docoutupid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DOCVALID", length = 7)
	public Date getDocvalid() {
		return this.docvalid;
	}

	public void setDocvalid(Date docvalid) {
		this.docvalid = docvalid;
	}

	@Column(name = "DOCPUBURL", length = 400)
	public String getDocpuburl() {
		return this.docpuburl;
	}

	public void setDocpuburl(String docpuburl) {
		this.docpuburl = docpuburl;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DOCPUBTIME", length = 7)
	public Date getDocpubtime() {
		return this.docpubtime;
	}

	public void setDocpubtime(Date docpubtime) {
		this.docpubtime = docpubtime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DOCRELTIME", length = 7)
	public Date getDocreltime() {
		return this.docreltime;
	}

	public void setDocreltime(Date docreltime) {
		this.docreltime = docreltime;
	}

	@Column(name = "CRUSER", length = 50)
	public String getCruser() {
		return this.cruser;
	}

	public void setCruser(String cruser) {
		this.cruser = cruser;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRTIME", length = 7)
	public Date getCrtime() {
		return this.crtime;
	}

	public void setCrtime(Date crtime) {
		this.crtime = crtime;
	}

	@Column(name = "DOCWORDSCOUNT", nullable = false, precision = 10, scale = 0)
	public Long getDocwordscount() {
		return this.docwordscount;
	}

	public void setDocwordscount(Long docwordscount) {
		this.docwordscount = docwordscount;
	}

	@Column(name = "DOCPRO", precision = 10, scale = 0)
	public Long getDocpro() {
		return this.docpro;
	}

	public void setDocpro(Long docpro) {
		this.docpro = docpro;
	}

	@Column(name = "RIGHTDEFINED", nullable = false, precision = 5, scale = 0)
	public int getRightdefined() {
		return this.rightdefined;
	}

	public void setRightdefined(int rightdefined) {
		this.rightdefined = rightdefined;
	}

	@Column(name = "TITLECOLOR", length = 20)
	public String getTitlecolor() {
		return this.titlecolor;
	}

	public void setTitlecolor(String titlecolor) {
		this.titlecolor = titlecolor;
	}

	@Column(name = "TEMPLATEID", precision = 10, scale = 0)
	public Long getTemplateid() {
		return this.templateid;
	}

	public void setTemplateid(Long templateid) {
		this.templateid = templateid;
	}

	@Column(name = "SCHEDULE", precision = 10, scale = 0)
	public Long getSchedule() {
		return this.schedule;
	}

	public void setSchedule(Long schedule) {
		this.schedule = schedule;
	}

	@Column(name = "DOCNO", length = 4000)
	public String getDocno() {
		return this.docno;
	}

	public void setDocno(String docno) {
		this.docno = docno;
	}

	@Column(name = "DOCFLAG", nullable = false, precision = 10, scale = 0)
	public Long getDocflag() {
		return this.docflag;
	}

	public void setDocflag(Long docflag) {
		this.docflag = docflag;
	}

	@Column(name = "EDITOR", length = 100)
	public String getEditor() {
		return this.editor;
	}

	public void setEditor(String editor) {
		this.editor = editor;
	}

	@Column(name = "ATTRIBUTE", length = 500)
	public String getAttribute() {
		return this.attribute;
	}

	public void setAttribute(String attribute) {
		this.attribute = attribute;
	}

	@Column(name = "HITSCOUNT", nullable = false, precision = 10, scale = 0)
	public Long getHitscount() {
		return this.hitscount;
	}

	public void setHitscount(Long hitscount) {
		this.hitscount = hitscount;
	}

	@Column(name = "SUBDOCTITLE", length = 500)
	public String getSubdoctitle() {
		return this.subdoctitle;
	}

	public String getDoccontent() {
		return doccontent;
	}

	public void setDoccontent(String doccontent) {
		this.doccontent = doccontent;
	}

	public String getDochtmlcon() {
		return dochtmlcon;
	}

	public void setDochtmlcon(String dochtmlcon) {
		this.dochtmlcon = dochtmlcon;
	}

	public String getDocpubhtmlcon() {
		return docpubhtmlcon;
	}

	public void setDocpubhtmlcon(String docpubhtmlcon) {
		this.docpubhtmlcon = docpubhtmlcon;
	}

	public void setSubdoctitle(String subdoctitle) {
		this.subdoctitle = subdoctitle;
	}

	@Column(name = "ATTACHPIC", precision = 5, scale = 0)
	public Integer getAttachpic() {
		return this.attachpic;
	}

	public void setAttachpic(Integer attachpic) {
		this.attachpic = attachpic;
	}

	@Column(name = "DOCLINK", length = 100)
	public String getDoclink() {
		return this.doclink;
	}

	public void setDoclink(String doclink) {
		this.doclink = doclink;
	}

	@Column(name = "DOCFILENAME", length = 50)
	public String getDocfilename() {
		return this.docfilename;
	}

	public void setDocfilename(String docfilename) {
		this.docfilename = docfilename;
	}

	@Column(name = "DOCFROMVERSION", precision = 10, scale = 0)
	public Long getDocfromversion() {
		return this.docfromversion;
	}

	public void setDocfromversion(Long docfromversion) {
		this.docfromversion = docfromversion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "OPERTIME", length = 7)
	public Date getOpertime() {
		return this.opertime;
	}

	public void setOpertime(Date opertime) {
		this.opertime = opertime;
	}

	@Column(name = "OPERUSER", length = 50)
	public String getOperuser() {
		return this.operuser;
	}

	public void setOperuser(String operuser) {
		this.operuser = operuser;
	}

	@Column(name = "FLOWOPERATIONMARK", length = 200)
	public String getFlowoperationmark() {
		return this.flowoperationmark;
	}

	public void setFlowoperationmark(String flowoperationmark) {
		this.flowoperationmark = flowoperationmark;
	}

	@Column(name = "FLOWPREOPERATIONMARK", length = 200)
	public String getFlowpreoperationmark() {
		return this.flowpreoperationmark;
	}

	public void setFlowpreoperationmark(String flowpreoperationmark) {
		this.flowpreoperationmark = flowpreoperationmark;
	}

	@Column(name = "FLOWOPERATIONMASKENUM", length = 2000)
	public String getFlowoperationmaskenum() {
		return this.flowoperationmaskenum;
	}

	public void setFlowoperationmaskenum(String flowoperationmaskenum) {
		this.flowoperationmaskenum = flowoperationmaskenum;
	}

	@Column(name = "DOCSOURCENAME", length = 100)
	public String getDocsourcename() {
		return this.docsourcename;
	}

	public void setDocsourcename(String docsourcename) {
		this.docsourcename = docsourcename;
	}

	@Column(name = "DOCLINKTO", length = 300)
	public String getDoclinkto() {
		return this.doclinkto;
	}

	public void setDoclinkto(String doclinkto) {
		this.doclinkto = doclinkto;
	}

	@Column(name = "DOCMIRRORTO", length = 300)
	public String getDocmirrorto() {
		return this.docmirrorto;
	}

	public void setDocmirrorto(String docmirrorto) {
		this.docmirrorto = docmirrorto;
	}

	@Column(name = "RANDOMSERIAL", length = 100)
	public String getRandomserial() {
		return this.randomserial;
	}

	public void setRandomserial(String randomserial) {
		this.randomserial = randomserial;
	}

	@Column(name = "POSTUSER", length = 50)
	public String getPostuser() {
		return this.postuser;
	}

	public void setPostuser(String postuser) {
		this.postuser = postuser;
	}

	@Column(name = "ISPAGEIMG", precision = 5, scale = 0)
	public Integer getIspageimg() {
		return this.ispageimg;
	}

	public void setIspageimg(Integer ispageimg) {
		this.ispageimg = ispageimg;
	}

	@Column(name = "PUBLISHDATE", length = 50)
	public String getPublishdate() {
		return this.publishdate;
	}

	public void setPublishdate(String publishdate) {
		this.publishdate = publishdate;
	}

	@Column(name = "PAGENUM", length = 20)
	public String getPagenum() {
		return this.pagenum;
	}

	public void setPagenum(String pagenum) {
		this.pagenum = pagenum;
	}

	@Column(name = "PAGENAME", length = 150)
	public String getPagename() {
		return this.pagename;
	}

	public void setPagename(String pagename) {
		this.pagename = pagename;
	}

	@Column(name = "PDFFILENAME", length = 150)
	public String getPdffilename() {
		return this.pdffilename;
	}

	public void setPdffilename(String pdffilename) {
		this.pdffilename = pdffilename;
	}

	@Column(name = "PAGEIMAGEFILENAME", length = 50)
	public String getPageimagefilename() {
		return this.pageimagefilename;
	}

	public void setPageimagefilename(String pageimagefilename) {
		this.pageimagefilename = pageimagefilename;
	}

	@Column(name = "MAP", length = 500)
	public String getMap() {
		return this.map;
	}

	public void setMap(String map) {
		this.map = map;
	}

	@Column(name = "YINTI", length = 200)
	public String getYinti() {
		return this.yinti;
	}

	public void setYinti(String yinti) {
		this.yinti = yinti;
	}

	@Column(name = "SITEID", nullable = false, precision = 10, scale = 0)
	public Long getSiteid() {
		return this.siteid;
	}

	public void setSiteid(Long siteid) {
		this.siteid = siteid;
	}

	@Column(name = "SRCSITEID", nullable = false, precision = 10, scale = 0)
	public Long getSrcsiteid() {
		return this.srcsiteid;
	}

	public void setSrcsiteid(Long srcsiteid) {
		this.srcsiteid = srcsiteid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DOCFIRSTPUBTIME", length = 7)
	public Date getDocfirstpubtime() {
		return this.docfirstpubtime;
	}

	public void setDocfirstpubtime(Date docfirstpubtime) {
		this.docfirstpubtime = docfirstpubtime;
	}

	@Column(name = "NODEID", precision = 22, scale = 0)
	public BigDecimal getNodeid() {
		return this.nodeid;
	}

	public void setNodeid(BigDecimal nodeid) {
		this.nodeid = nodeid;
	}

	@Column(name = "ORDERID", precision = 22, scale = 0)
	public BigDecimal getOrderid() {
		return this.orderid;
	}

	public void setOrderid(BigDecimal orderid) {
		this.orderid = orderid;
	}

	@Column(name = "CRDEPT", length = 400)
	public String getCrdept() {
		return this.crdept;
	}

	public void setCrdept(String crdept) {
		this.crdept = crdept;
	}

	@Column(name = "DOCFORM", precision = 5, scale = 0)
	public Integer getDocform() {
		return docform;
	}

	public void setDocform(Integer docform) {
		this.docform = docform;
	}

	@Column(name = "DOCLEVEL", length = 20)
	public String getDoclevel() {
		return doclevel;
	}

	public void setDoclevel(String doclevel) {
		this.doclevel = doclevel;
	}
}