package com.wondersgroup.scxj.portal.modules.law.entity;

// Generated 2014-1-20 14:16:03 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.wondersgroup.scxj.portal.common.persistence.BaseEntity;

/**
 * Holiday generated by hbm2java
 */
@Entity
@Table(name = "XWCMHOLIDAY")
public class Holiday extends BaseEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;


	private Long id;
	private String holidayname;
	private String holidayds;
	private String holidaytime;
	private String cruser;
	private Date crtime;
	private Integer status;

	public Holiday() {
	}

	public Holiday(Long messagelogsid) {
		this.id = messagelogsid;
	}

	public Holiday(Long id, String holidayname,
			String holidayds,
			String holidaytime, String cruser, Date crtime, Integer status) {
		this.id = id;
		this.holidayname = holidayname;
		this.holidayds = holidayds;
		this.holidaytime = holidaytime;
		this.cruser = cruser;
		this.crtime = crtime;
		this.status = status;
	}

	@Id
	@TableGenerator(name = "TABLE_HOLIDAY_ID_GENERATOR", table = "WCMID", pkColumnName = "TABLENAME", pkColumnValue = "XWCMHOLIDAY", valueColumnName = "NEXTID", initialValue = 1, allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "TABLE_HOLIDAY_ID_GENERATOR")
	@Column(name = "HOLIDAYID", nullable = false)
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	

	@Column(name = "CRUSER", length = 30)
	public String getCruser() {
		return this.cruser;
	}

	public void setCruser(String cruser) {
		this.cruser = cruser;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRTIME", length = 7)
	public Date getCrtime() {
		return this.crtime;
	}

	public void setCrtime(Date crtime) {
		this.crtime = crtime;
	}


	@Column(name = "HOLIDAYNAME", length = 50)
	public String getHolidayname() {
		return holidayname;
	}

	public void setHolidayname(String holidayname) {
		this.holidayname = holidayname;
	}

	@Column(name = "HOLIDAYDS", length = 500)
	public String getHolidayds() {
		return holidayds;
	}

	public void setHolidayds(String holidayds) {
		this.holidayds = holidayds;
	}

	@Column(name = "HOLIDAYTIME", length = 50)
	public String getHolidaytime() {
		return holidaytime;
	}

	public void setHolidaytime(String holidaytime) {
		this.holidaytime = holidaytime;
	}

	@Column(name = "STATUS", length = 50)
	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}
	

}
