package com.wondersgroup.scxj.portal.modules.law.entity;

// Generated 2014-3-28 23:55:25 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Transient;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.google.common.collect.Lists;
import com.wondersgroup.scxj.portal.common.persistence.BaseEntity;

/**
 * Xwcmsearchapply generated by hbm2java
 */
@Entity
@Table(name = "XWCMSEARCHAPPLY")
@DynamicInsert
@DynamicUpdate
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class SearchApply extends BaseEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	public static final String SEARCHAPPID = "searchappid";
	private Long searchappid;
	private String suspectsname;
	private String brief;
	private String lawyername;
	private String lawyeridcode;
	private String lawfirmname;
	private String lawyertel;
	private String lawyeremail;
	private String lawyercardnum;
	private String searchcode;
	private String searchpass;
	private Long groupid;
	private String groupname;
	private String dealcontent;
	private Integer dealstatus;
	private Date dealdate;
	private String dealusername;
	private String caseid;
	private Date linkdate;
	private Long applyway;
	private String ext;
	private Date crtime;
	private String personid;
	private String dlstage;
	private String czdlstage;
	private Date enddate;
	private String caseaccepctnum;
	private String importcaseaccepctnum;
	private String relation;

	private String lawyerRegTel;
	private String lawyerRegEmail;
	private Date casecrtime;
	private String caseapprovedate;
	private String caseacceptdate;
	private String casestage;

	private List<LawAppendix> lawAppendixs = Lists.newArrayList();

	public SearchApply() {
	}

	public SearchApply(Long searchappid) {
		this.searchappid = searchappid;
	}

	public SearchApply(Long searchappid, String suspectsname, String brief,
			String lawyername, String lawyeridcode, String lawfirmname,
			String lawyertel, String lawyeremail, String lawyercardnum,
			String searchcode, String searchpass, Long groupid,
			String groupname, String dealcontent, Integer dealstatus,
			Date dealdate, String dealusername, String caseid, Date linkdate,
			Long applyway, String ext, Date crtime, String personid,
			String dlstage, String czdlstage, Date enddate,
			String caseaccepctnum, String importcaseaccepctnum, String relation) {
		this.searchappid = searchappid;
		this.suspectsname = suspectsname;
		this.brief = brief;
		this.lawyername = lawyername;
		this.lawyeridcode = lawyeridcode;
		this.lawfirmname = lawfirmname;
		this.lawyertel = lawyertel;
		this.lawyeremail = lawyeremail;
		this.lawyercardnum = lawyercardnum;
		this.searchcode = searchcode;
		this.searchpass = searchpass;
		this.groupid = groupid;
		this.groupname = groupname;
		this.dealcontent = dealcontent;
		this.dealstatus = dealstatus;
		this.dealdate = dealdate;
		this.dealusername = dealusername;
		this.caseid = caseid;
		this.linkdate = linkdate;
		this.applyway = applyway;
		this.ext = ext;
		this.crtime = crtime;
		this.personid = personid;
		this.dlstage = dlstage;
		this.czdlstage = czdlstage;
		this.enddate = enddate;
		this.caseaccepctnum = caseaccepctnum;
		this.importcaseaccepctnum = importcaseaccepctnum;
		this.relation = relation;
	}

	@Id
	@TableGenerator(name = "TABLE_SEARCH_APPLY_ID_GENERATOR", table = "WCMID", pkColumnName = "TABLENAME", pkColumnValue = "XWCMSEARCHAPPLY", valueColumnName = "NEXTID", initialValue = 1, allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "TABLE_SEARCH_APPLY_ID_GENERATOR")
	@Column(name = "SEARCHAPPID", nullable = false)
	public Long getSearchappid() {
		return this.searchappid;
	}

	public void setSearchappid(Long searchappid) {
		this.searchappid = searchappid;
	}

	@Column(name = "SUSPECTSNAME", nullable = true)
	public String getSuspectsname() {
		return this.suspectsname;
	}

	public void setSuspectsname(String suspectsname) {
		this.suspectsname = suspectsname;
	}

	@Column(name = "BRIEF", nullable = true, length = 2000)
	public String getBrief() {
		return this.brief;
	}

	public void setBrief(String brief) {
		this.brief = brief;
	}

	@Column(name = "LAWYERNAME", nullable = false, length = 50)
	public String getLawyername() {
		return this.lawyername;
	}

	public void setLawyername(String lawyername) {
		this.lawyername = lawyername;
	}

	@Column(name = "LAWYERIDCODE", nullable = false, length = 50)
	public String getLawyeridcode() {
		return this.lawyeridcode;
	}

	public void setLawyeridcode(String lawyeridcode) {
		this.lawyeridcode = lawyeridcode;
	}

	@Column(name = "LAWFIRMNAME", nullable = false, length = 50)
	public String getLawfirmname() {
		return this.lawfirmname;
	}

	public void setLawfirmname(String lawfirmname) {
		this.lawfirmname = lawfirmname;
	}

	@Column(name = "LAWYERTEL", nullable = true, length = 50)
	public String getLawyertel() {
		return this.lawyertel;
	}

	public void setLawyertel(String lawyertel) {
		this.lawyertel = lawyertel;
	}

	@Column(name = "LAWYEREMAIL", nullable = true, length = 50)
	public String getLawyeremail() {
		return this.lawyeremail;
	}

	public void setLawyeremail(String lawyeremail) {
		this.lawyeremail = lawyeremail;
	}

	@Column(name = "LAWYERCARDNUM", nullable = false, length = 50)
	public String getLawyercardnum() {
		return this.lawyercardnum;
	}

	public void setLawyercardnum(String lawyercardnum) {
		this.lawyercardnum = lawyercardnum;
	}

	@Column(name = "SEARCHCODE", nullable = false, length = 50)
	public String getSearchcode() {
		return this.searchcode;
	}

	public void setSearchcode(String searchcode) {
		this.searchcode = searchcode;
	}

	@Column(name = "SEARCHPASS", nullable = false, length = 50)
	public String getSearchpass() {
		return this.searchpass;
	}

	public void setSearchpass(String searchpass) {
		this.searchpass = searchpass;
	}

	@Column(name = "GROUPID", nullable = false)
	public Long getGroupid() {
		return this.groupid;
	}

	public void setGroupid(Long groupid) {
		this.groupid = groupid;
	}

	@Column(name = "GROUPNAME", nullable = false, length = 50)
	public String getGroupname() {
		return this.groupname;
	}

	public void setGroupname(String groupname) {
		this.groupname = groupname;
	}

	@Column(name = "DEALCONTENT", nullable = true, length = 2000)
	public String getDealcontent() {
		return this.dealcontent;
	}

	public void setDealcontent(String dealcontent) {
		this.dealcontent = dealcontent;
	}

	@Column(name = "DEALSTATUS", nullable = true)
	public Integer getDealstatus() {
		return this.dealstatus;
	}

	public void setDealstatus(Integer dealstatus) {
		this.dealstatus = dealstatus;
	}

	@Column(name = "DEALDATE", nullable = true)
	public Date getDealdate() {
		return this.dealdate;
	}

	public void setDealdate(Date dealdate) {
		this.dealdate = dealdate;
	}

	@Column(name = "DEALUSERNAME", nullable = true, length = 50)
	public String getDealusername() {
		return this.dealusername;
	}

	public void setDealusername(String dealusername) {
		this.dealusername = dealusername;
	}

	@Column(name = "CASEID", nullable = true)
	public String getCaseid() {
		return this.caseid;
	}

	public void setCaseid(String caseid) {
		this.caseid = caseid;
	}

	@Column(name = "LINKDATE", nullable = true)
	public Date getLinkdate() {
		return this.linkdate;
	}

	public void setLinkdate(Date linkdate) {
		this.linkdate = linkdate;
	}

	@Column(name = "APPLYWAY", nullable = true)
	public Long getApplyway() {
		return this.applyway;
	}

	public void setApplyway(Long applyway) {
		this.applyway = applyway;
	}

	@Column(name = "EXT", nullable = true)
	public String getExt() {
		return this.ext;
	}

	public void setExt(String ext) {
		this.ext = ext;
	}

	@Column(name = "CRTIME", nullable = true)
	public Date getCrtime() {
		return this.crtime;
	}

	public void setCrtime(Date crtime) {
		this.crtime = crtime;
	}

	@Column(name = "PERSONID", nullable = true)
	public String getPersonid() {
		return this.personid;
	}

	public void setPersonid(String personid) {
		this.personid = personid;
	}

	@Column(name = "DLSTAGE", nullable = true)
	public String getDlstage() {
		return this.dlstage;
	}

	public void setDlstage(String dlstage) {
		this.dlstage = dlstage;
	}

	@Column(name = "CZDLSTAGE", nullable = true)
	public String getCzdlstage() {
		return this.czdlstage;
	}

	public void setCzdlstage(String czdlstage) {
		this.czdlstage = czdlstage;
	}

	@Column(name = "ENDDATE", nullable = true)
	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	@Column(name = "CASEACCEPCTNUM", nullable = true)
	public String getCaseaccepctnum() {
		return this.caseaccepctnum;
	}

	public void setCaseaccepctnum(String caseaccepctnum) {
		this.caseaccepctnum = caseaccepctnum;
	}

	@Column(name = "IMPORTCASEACCEPCTNUM", nullable = true)
	public String getImportcaseaccepctnum() {
		return this.importcaseaccepctnum;
	}

	public void setImportcaseaccepctnum(String importcaseaccepctnum) {
		this.importcaseaccepctnum = importcaseaccepctnum;
	}

	@Column(name = "RELATION", nullable = true)
	public String getRelation() {
		return this.relation;
	}

	public void setRelation(String relation) {
		this.relation = relation;
	}

	@Transient
	public String getLawyerRegTel() {
		return lawyerRegTel;
	}

	public void setLawyerRegTel(String lawyerRegTel) {
		this.lawyerRegTel = lawyerRegTel;
	}

	@Transient
	public String getLawyerRegEmail() {
		return lawyerRegEmail;
	}

	public void setLawyerRegEmail(String lawyerRegEmail) {
		this.lawyerRegEmail = lawyerRegEmail;
	}

	@Transient
	public Date getCasecrtime() {
		return casecrtime;
	}

	public void setCasecrtime(Date casecrtime) {
		this.casecrtime = casecrtime;
	}

	@Transient
	public String getCaseapprovedate() {
		return caseapprovedate;
	}

	public void setCaseapprovedate(String caseapprovedate) {
		this.caseapprovedate = caseapprovedate;
	}

	@Transient
	public String getCaseacceptdate() {
		return caseacceptdate;
	}

	public void setCaseacceptdate(String caseacceptdate) {
		this.caseacceptdate = caseacceptdate;
	}

	@Transient
	public String getCasestage() {
		return casestage;
	}

	public void setCasestage(String casestage) {
		this.casestage = casestage;
	}

	@Transient
	@JsonIgnore
	public List<LawAppendix> getLawAppendixs() {
		return lawAppendixs;
	}

	public void setLawAppendixs(List<LawAppendix> lawAppendixs) {
		this.lawAppendixs = lawAppendixs;
	}

}
