package com.wondersgroup.scxj.portal.modules.law.entity;

// Generated 2014-1-20 14:16:03 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Wcmuser generated by hbm2java
 */
@Entity
@Table(name = "WCMUSER")
public class WcmUser implements java.io.Serializable {

	private long userid;
	private int status;
	private String username;
	private String password;
	private String nickname;
	private String truename;
	private String address;
	private String tel;
	private String mobile;
	private String email;
	private String reminderquestion;
	private String reminderanswer;
	private Integer ifpubmyinfo;
	private Date applytime;
	private Date regtime;
	private long logintimes;
	private Date logintime;
	private Date logouttime;
	private Integer msginterval;
	private Integer viewinterval;
	private String attribute;
	private String cruser;
	private Date crtime;
	private long price;
	private int isdeleted;
	private long passwordlev;
	private Long viewdoclevel;

	public WcmUser() {
	}

	public WcmUser(long userid, int status, String username, String password,
			long logintimes, long price, int isdeleted, long passwordlev) {
		this.userid = userid;
		this.status = status;
		this.username = username;
		this.password = password;
		this.logintimes = logintimes;
		this.price = price;
		this.isdeleted = isdeleted;
		this.passwordlev = passwordlev;
	}

	public WcmUser(long userid, int status, String username, String password,
			String nickname, String truename, String address, String tel,
			String mobile, String email, String reminderquestion,
			String reminderanswer, Integer ifpubmyinfo, Date applytime,
			Date regtime, long logintimes, Date logintime, Date logouttime,
			Integer msginterval, Integer viewinterval, String attribute,
			String cruser, Date crtime, long price, int isdeleted,
			long passwordlev, Long viewdoclevel) {
		this.userid = userid;
		this.status = status;
		this.username = username;
		this.password = password;
		this.nickname = nickname;
		this.truename = truename;
		this.address = address;
		this.tel = tel;
		this.mobile = mobile;
		this.email = email;
		this.reminderquestion = reminderquestion;
		this.reminderanswer = reminderanswer;
		this.ifpubmyinfo = ifpubmyinfo;
		this.applytime = applytime;
		this.regtime = regtime;
		this.logintimes = logintimes;
		this.logintime = logintime;
		this.logouttime = logouttime;
		this.msginterval = msginterval;
		this.viewinterval = viewinterval;
		this.attribute = attribute;
		this.cruser = cruser;
		this.crtime = crtime;
		this.price = price;
		this.isdeleted = isdeleted;
		this.passwordlev = passwordlev;
		this.viewdoclevel = viewdoclevel;
	}

	@Id
	@Column(name = "USERID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getUserid() {
		return this.userid;
	}

	public void setUserid(long userid) {
		this.userid = userid;
	}

	@Column(name = "STATUS", nullable = false, precision = 5, scale = 0)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "USERNAME", nullable = false, length = 100)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PASSWORD", nullable = false, length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "NICKNAME", length = 100)
	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	@Column(name = "TRUENAME", length = 128)
	public String getTruename() {
		return this.truename;
	}

	public void setTruename(String truename) {
		this.truename = truename;
	}

	@Column(name = "ADDRESS", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "TEL", length = 100)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "MOBILE", length = 100)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "EMAIL", length = 2000)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "REMINDERQUESTION", length = 200)
	public String getReminderquestion() {
		return this.reminderquestion;
	}

	public void setReminderquestion(String reminderquestion) {
		this.reminderquestion = reminderquestion;
	}

	@Column(name = "REMINDERANSWER", length = 200)
	public String getReminderanswer() {
		return this.reminderanswer;
	}

	public void setReminderanswer(String reminderanswer) {
		this.reminderanswer = reminderanswer;
	}

	@Column(name = "IFPUBMYINFO", precision = 5, scale = 0)
	public Integer getIfpubmyinfo() {
		return this.ifpubmyinfo;
	}

	public void setIfpubmyinfo(Integer ifpubmyinfo) {
		this.ifpubmyinfo = ifpubmyinfo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "APPLYTIME", length = 7)
	public Date getApplytime() {
		return this.applytime;
	}

	public void setApplytime(Date applytime) {
		this.applytime = applytime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "REGTIME", length = 7)
	public Date getRegtime() {
		return this.regtime;
	}

	public void setRegtime(Date regtime) {
		this.regtime = regtime;
	}

	@Column(name = "LOGINTIMES", nullable = false, precision = 10, scale = 0)
	public long getLogintimes() {
		return this.logintimes;
	}

	public void setLogintimes(long logintimes) {
		this.logintimes = logintimes;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LOGINTIME", length = 7)
	public Date getLogintime() {
		return this.logintime;
	}

	public void setLogintime(Date logintime) {
		this.logintime = logintime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LOGOUTTIME", length = 7)
	public Date getLogouttime() {
		return this.logouttime;
	}

	public void setLogouttime(Date logouttime) {
		this.logouttime = logouttime;
	}

	@Column(name = "MSGINTERVAL", precision = 5, scale = 0)
	public Integer getMsginterval() {
		return this.msginterval;
	}

	public void setMsginterval(Integer msginterval) {
		this.msginterval = msginterval;
	}

	@Column(name = "VIEWINTERVAL", precision = 5, scale = 0)
	public Integer getViewinterval() {
		return this.viewinterval;
	}

	public void setViewinterval(Integer viewinterval) {
		this.viewinterval = viewinterval;
	}

	@Column(name = "ATTRIBUTE", length = 1000)
	public String getAttribute() {
		return this.attribute;
	}

	public void setAttribute(String attribute) {
		this.attribute = attribute;
	}

	@Column(name = "CRUSER", length = 100)
	public String getCruser() {
		return this.cruser;
	}

	public void setCruser(String cruser) {
		this.cruser = cruser;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRTIME", length = 7)
	public Date getCrtime() {
		return this.crtime;
	}

	public void setCrtime(Date crtime) {
		this.crtime = crtime;
	}

	@Column(name = "PRICE", nullable = false, precision = 10, scale = 0)
	public long getPrice() {
		return this.price;
	}

	public void setPrice(long price) {
		this.price = price;
	}

	@Column(name = "ISDELETED", nullable = false, precision = 5, scale = 0)
	public int getIsdeleted() {
		return this.isdeleted;
	}

	public void setIsdeleted(int isdeleted) {
		this.isdeleted = isdeleted;
	}

	@Column(name = "PASSWORDLEV", nullable = false, precision = 10, scale = 0)
	public long getPasswordlev() {
		return this.passwordlev;
	}

	public void setPasswordlev(long passwordlev) {
		this.passwordlev = passwordlev;
	}

	@Column(name = "VIEWDOCLEVEL", precision = 10, scale = 0)
	public Long getViewdoclevel() {
		return this.viewdoclevel;
	}

	public void setViewdoclevel(Long viewdoclevel) {
		this.viewdoclevel = viewdoclevel;
	}

}
